### ISSUE TITLE
Allow to define events

### ISSUE THREAD

**Issue by famoser** [famoser/agnes#1]
Allow events to be defined which execute after or before a command executes.

Example & specification format:
```
events:
  deploy:
    before:
      - filter:
          environment: [staging]
        command: copy_shared
        arguments: { source: production }
    after:
      - filter:
          environment: [dev]
        command: fixtures
```
