### ISSUE TITLE
Introduce release provider

### ISSUE THREAD

**Issue by famoser** [famoser/agnes#20]
Introduce release providers, which replaces the designated github node. This level of abstraction removes tight coupling with github.

Proposed config:
```yml
release:
  provider:
    type: github
    api_token: null
    repository: famoser/agnes
```

The clean abstraction resolves #16
